### ISSUE TITLE
Using in React

### ISSUE THREAD

**Issue by hector** [fefanto/fontaudio#2]
Hi, great work!!
I am planning to use this on the webpage with React.js.
I am just curious if you recommend a particular way to do it.

I was thinking:
- install with npm/yarn
- import css from node_modules
- use as html elements `<i class=" icon-fad-AR"></i>`

**Comment by fefanto** [comment]
Hello there! thanks!

Unfortunately, fontaudio is not (yet) published as a node package, so if you want to use it just get the .css & .ttf file in ./font and use them in your project.

This brings us to the fact that I did not test yet this package in a web project - I just included the .css created by default by the icon-font-generator package I'm using. 

If you dare to go ahead with this and find any problem just report it here and I'll try to fix it or try to find someone more expert on web font usage to help out.

thanks again!

**Comment by hector** [comment]
Hi!

Since for now I will only use one icon I just copied the contents of the svg directly to html.
It is raw but works smoothly :)

Thanks!
