### ISSUE TITLE
Using the Juce module, some icons are completely filled in

### ISSUE THREAD

**Issue by codecat** [fefanto/fontaudio#3]
So I'm using the Juce module, and trying to draw an icon with this code:

```
fontaudio::RenderedIcon icon = sharedFontAudio->getIcon(fontaudio::Stereo, 20, m_color);
sharedFontAudio->drawCenterdAt(g, icon, rect.toNearestInt());
```

Which gives this result, instead of what I expected from [the screenshot](https://raw.githubusercontent.com/fefanto/fontaudio/master/screenshots/fad-screenshot.png).

![image](https://user-images.githubusercontent.com/136534/66340334-3acc6600-e945-11e9-99d1-68d0a11d47ab.png)

The code for `getIcon` looks okay to me, so maybe the problem is with the font file instead? (Not entirely sure as I didn't look too much into this yet, sorry!)

**Edit:** This code will also cause it to happen:

```
g.setFont(sharedFontAudio->getFont(16.0f));
g.drawText(fontaudio::Stereo, rect, Justification::centred);
```

**Comment by fefanto** [comment]
Hello - strange indeed, the juce demo pip tests all Icons, but lots of them are tested using the drawfittedtext call - I'll shortly make another test using the drawtext and drawimage then post the results here and eventually fix it.
Does the [Juce demo](https://github.com/fefanto/fontaudio#using-the-juce-module)  in the repo show the same problems on your side?

**Comment by codecat** [comment]
Yep, the demo also looks like that to me:

![image](https://user-images.githubusercontent.com/136534/66478706-3f0a9780-ea9b-11e9-8def-0f332a1d72c6.png)

A thing to note - I am using the Juce code from their develop branch (except whatever's generated by projucer), so that might have something to do with it.

**Comment by codecat** [comment]
Small update, it doesn't happen on MacOS, where I'm not using the latest Dev branch.

**Comment by fefanto** [comment]
hello there, sorry for this taking eons - master should now be fully compatible with windows - no more filled in Icons. cheers!

**Comment by codecat** [comment]
Thanks for the fix!!
